---
<% if fog_file = File.expand_path('~/.fog') and File.exists?(fog_file)
  fog_file = YAML.load_file(fog_file)
  ENV['AWS_ACCESS_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_access_key_id']
  ENV['AWS_SECRET_ACCESS_KEY'] ||= fog_file.fetch('travis-ci', {})['aws_secret_access_key']
  ENV['AWS_KEYPAIR_NAME'] ||= fog_file.fetch('travis-ci', {})['aws_keypair_name']
  ENV['EC2_SSH_KEY_PATH'] ||= File.expand_path('~/.ssh/id_rsa_kitchen_ec2')
end %>
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  require_chef_omnibus: "11.4.4"
provisioner:
  name: chef_solo
  attributes:
    test_kitchen: true
    opsworks-migrations:
      command: touch migration-executed
    opsworks:
      ruby_version: '2.1'
      ruby_stack: "ruby"
    deploy:
      test_app:
        ssl_support: false
        application: "test_app"
        database: {}
        ssl_certificate_ca: null
        migrate: false
        deploy_to: "/srv/www/test_app"
        environment: {}
        scm:
          scm_type: "other"
        ssl_certificate_key: null
        rails_env: "test"
        auto_bundle_on_deploy: false
        environment_variables: {}
        ssl_certificate: null
        restart_command: null
        symlinks:
          log: "log"
          system: "public/system"
          pids: "tmp/pids"
        deploying_user: null
        application_type: "other"
        memcached:
          port: 11211
          host: null
        symlink_before_migrate:
          config/database.yml: "config/database.yml"
          config/memcached.yml: "config/memcached.yml"
        sleep_before_restart: 0
        mounted_at: null
        domains:
          - "localhost"
        document_root: "public"

platforms:
  - name: amzn-2014-09-1
    driver_plugin: ec2
    driver_config:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
      username: ec2-user
      flavor_id: c3.large
      image_id: ami-0268d56a
      region: us-east-1
      availability_zone: us-east-1b
      security_group_ids: ['ci-testing']
      interface: public
      tags:
        Name: <%= "#{ENV['CI'] ? 'travis-ci' : ENV['USER']}-opsworks-migrations-kitchen" %>
        Env: public

suites:
  - name: default
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[dependencies]
      - recipe[opsworks-migrations::_test-setup]
      - recipe[opsworks-migrations::default]
    attributes:
